version: "3"

services:
  adguardhome:
    image: adguard/adguardhome
    container_name: sniproxy-adguardhome
    restart: unless-stopped
    logging:
      options:
        max-size: "3m"
    network_mode: "host"
    volumes:
      - ./conf:/opt/adguardhome/conf

  nginx:
    image: nginx:alpine
    container_name: sniproxy-nginx
    restart: unless-stopped
    logging:
      options:
        max-size: "3m"
    network_mode: "host"
    volumes:
      - ./conf:/etc/nginx
